version: '3.8'
services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MONGO_INITDB_DATABASE: gipfel-server
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    command: ["--replSet", "rs0", "--noauth"]

volumes:
  mongo_data: 